version: '3'

services:
  web:
    image: kenura/soul-nest_backend:latest
    ports:
      - "8002:8000"    

  nginx:
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web